contact_links:
  - name: Question
    about: "Please use one of the community spaces instead for questions or general discussions."
    url: https://ziglang.org/community
  - name: C Translation
    about: "Issues related to `zig translate-c` are tracked separately."
    url: https://codeberg.org/ziglang/translate-c
